import customtkinter


customtkinter.set_appearance_mode("Dark")
customtkinter.set_default_color_theme("blue")
janela = customtkinter.CTk()
janela.title("Sistema de gerenciamento")
janela.geometry("800x400")
frame1 = customtkinter.CTkFrame(janela, width=190, height=390, corner_radius=7)
frame1.pack_propagate(False)
frame1.grid(row=0, column=0, padx=5, pady=5)
frame2 = customtkinter.CTkFrame(janela, width=590, height=390, corner_radius=7)
frame2.grid_propagate(False)
frame2.grid(row=0, column=1, padx=5, pady=5)

titulo01 = customtkinter.CTkLabel(frame1, text="Nome do Sistema", font=("Arial", 20, "bold"))
titulo01.pack(pady=50)
botao01 = customtkinter.CTkButton(frame1, text="Cadastrar")
botao01.pack()
botao02 = customtkinter.CTkButton(frame1, fg_color="#232323", text="Editar")
botao02.pack(pady=10)
botao03 = customtkinter.CTkButton(frame1, text="Saida")
botao03.pack()
botao04 = customtkinter.CTkButton(frame1, text="Entrada")
botao04.pack(pady=10)
botao05 = customtkinter.CTkButton(frame1, text="Relatório")
botao05.pack()

titulo02 = customtkinter.CTkLabel(frame2, text="Cadastro de Produto", font=("Arial", 20, "bold"))
titulo02.grid(row=0, column=1, pady=20)
texto01 = customtkinter.CTkLabel(frame2, text="Nome do Produto:")
texto01.grid(row=1, column=0, padx=10, sticky="e")
texto02 = customtkinter.CTkLabel(frame2, text="Preço (R$):")
texto02.grid(row=2, column=0, padx=10, sticky="e")
texto03 = customtkinter.CTkLabel(frame2, text="Descrição:")
texto03.grid(row=3, column=0, padx=10, sticky="ne")
entrada01 = customtkinter.CTkEntry(frame2, width=300, placeholder_text="digite o nome do produto")
entrada01.grid(row=1, column=1, padx=10, sticky="w")
entrada02 = customtkinter.CTkEntry(frame2, width=80, placeholder_text="0.00")
entrada02.grid(row=2, column=1, pady=10, padx=10, sticky="w")
caixa_texto = customtkinter.CTkTextbox(frame2, width=300, height=80)
caixa_texto.grid(row=3, column=1, padx=10, sticky="w")
botao1 = customtkinter.CTkButton(frame2, text="salvar", width=80)
botao1.grid(row=4, column=1, padx=10, pady=10, sticky="e")
janela.mainloop()
